### ISSUE TITLE
byte thing

### ISSUE THREAD

**Issue by auskimus** [sorscode/CC1101_Full_SPI#1]
Hi, 
I am trying to use your code but line # 149 < byte thing[] = {0x20, 0x48, 0x69, 0x20, 0x50, 0x75, 0x6e, 0x6b}; > seems puzzling for me,  I am trying to find out how the Hex registers in the byte thing array are related to the CC1101 default values  or any other registers in the code in case if I want change or modify frequency registers on the SmartRF Studio.

Thank you in advance

**Comment by sorscode** [comment]
@auskimus so I'm going to assume you are looking at file `cc1101_spi_tx/cc1101_spi_tx.ino`. Line 149 has nothing to do with the registers for frequency. 

`byte thing[] = {0x20, 0x48, 0x69, 0x20, 0x50, 0x75, 0x6e, 0x6b};`

If you convert hex to unicode, that translates to `Hi Punk`.

If you look at line 146, the hex code for that is on 147 same goes for line 148, the hex code is line 149 which you are asking about.

To change the channel/frequency you would do that in the `void cc1101_config()` call.

**Comment by auskimus** [comment]
Hi Danny
Thanks for the reply, yes its cc1101_spi_tx/cc1101_spi_tx.ino 
that is very interesting so  Hi Punk (in hex)  could be any word or phrase then  copied to data.data without affecting the rest of the code?
Kind Regards

**Comment by sorscode** [comment]
@auskimus Correct, the part you are looking at is a phrase that will be transmit every 3000ms in that example. This was a very general example so someone could see how the transmission of data worked. Glad you are finding this repository helpful. Let me know if you have any other questions.

**Comment by auskimus** [comment]
Hi Danny

Thank you very much for the clear clarification, now just a question from a friend who was digging hard with me to find out that registers which holds “Hi Punk”, how the receiver will interpret the hex via Unicode or it will be received in hex? 

Kind Regards 
Mustafa Monim

**Comment by sorscode** [comment]
@auskimus it will be received in hex, so you then will need to convert it, which `cc1101_spi_rx/cc1101_spi_rx.ino` does.

**Comment by auskimus** [comment]
Hi Danny

Thank you for the great repository and kind assistance.

Kind Regards 
Mustafa Monim

**Comment by sorscode** [comment]
@auskimus Anytime!
